// JavaScript to render elements in a proper periodic table layout
document.addEventListener("DOMContentLoaded", () => {
    const periodicTableContainer = document.getElementById("periodicTable");

    elements.forEach((element) => {
        const elementDiv = document.createElement("div");
        elementDiv.classList.add("element", element.category);
        elementDiv.style.gridColumn = element.groupNumber; // Place elements in correct group (column)
        elementDiv.style.gridRow = element.periodNumber; // Place elements in correct period (row)

        elementDiv.innerHTML = `
            <p>${element.symbol}</p>
            <p>${element.atomicNumber}</p>
        `;

        // Add hover event for showing element details
        elementDiv.addEventListener("mouseenter", () => showElementDetails(element));

        // Add click event for element interactivity
        elementDiv.addEventListener("click", () => displayElementModal(element));

        periodicTableContainer.appendChild(elementDiv);
    });
});

function showElementDetails(element) {
    const detailsContent = document.getElementById("detailsContent");
    detailsContent.innerHTML = `
        <img src="${element.image}" alt="${element.name}">
        <p><strong>Name:</strong> ${element.name}</p>
        <p><strong>Atomic Number:</strong> ${element.atomicNumber}</p>
        <p><strong>Symbol:</strong> ${element.symbol}</p>
        <p><strong>Category:</strong> ${element.category}</p>
        <p><strong>Electronic Configuration:</strong> ${element.electronicConfiguration}</p>
    `;
    document.getElementById("elementDetails").style.display = "block";
}

function displayElementModal(element) {
    // Modal or any other interactivity logic
    alert(`You clicked on ${element.name}`);
}
const elements = [
    {
        name: "Hydrogen",
        symbol: "H",
        atomicNumber: 1,
        massNumber: 1,
        meltingPoint: "-259.14 °C",
        boilingPoint: "-252.87 °C",
        atomicRadius: "53 pm",
        electrons: 1,
        protons: 1,
        neutrons: 0,
        electronicConfiguration: "1s¹",
        yearOfDiscovery: 1766,
        discoveredBy: "Henry Cavendish",
        groupNumber: 1,
        blockName: "s",
        periodNumber: 1,
        density: "0.08988 g/L",
        image: "https://www.chemicalelements.com/images/elements/hydrogen.png",
        category: "alkali"
    },
    {
        name: "Helium",
        symbol: "He",
        atomicNumber: 2,
        massNumber: 4,
        meltingPoint: "-272.20 °C",
        boilingPoint: "-268.93 °C",
        atomicRadius: "31 pm",
        electrons: 2,
        protons: 2,
        neutrons: 2,
        electronicConfiguration: "1s²",
        yearOfDiscovery: 1895,
        discoveredBy: "Sir William Ramsay",
        groupNumber: 18,
        blockName: "s",
        periodNumber: 1,
        density: "0.1786 g/L",
        image: "https://www.chemicalelements.com/images/elements/helium.png",
        category: "noble-gases"
    },
    {
        name: "Lithium",
        symbol: "Li",
        atomicNumber: 3,
        massNumber: 7,
        meltingPoint: "180.54 °C",
        boilingPoint: "1590 °C",
        atomicRadius: "152 pm",
        electrons: 3,
        protons: 3,
        neutrons: 4,
        electronicConfiguration: "1s² 2s¹",
        yearOfDiscovery: 1817,
        discoveredBy: "Johann August Arfvedson",
        groupNumber: 1,
        blockName: "s",
        periodNumber: 2,
        density: "0.534 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/lithium.png",
        category: "alkali"
    },
    {
        name: "Beryllium",
        symbol: "Be",
        atomicNumber: 4,
        massNumber: 9,
        meltingPoint: "1287 °C",
        boilingPoint: "2469 °C",
        atomicRadius: "112 pm",
        electrons: 4,
        protons: 4,
        neutrons: 5,
        electronicConfiguration: "1s² 2s²",
        yearOfDiscovery: 1798,
        discoveredBy: "Louis Nicolas Vauquelin",
        groupNumber: 2,
        blockName: "s",
        periodNumber: 2,
        density: "1.848 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/beryllium.png",
        category: "alkali-earth"
    },
    {
        name: "Carbon",
        symbol: "C",
        atomicNumber: 6,
        massNumber: 12,
        meltingPoint: "3550 °C",
        boilingPoint: "4027 °C",
        atomicRadius: "70 pm",
        electrons: 6,
        protons: 6,
        neutrons: 6,
        electronicConfiguration: "1s² 2s² 2p²",
        yearOfDiscovery: "Ancient",
        discoveredBy: "Multiple sources",
        groupNumber: 14,
        blockName: "p",
        periodNumber: 2,
        density: "2.267 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/carbon.png",
        category: "nonmetals"
    },
    {
        name: "Nitrogen",
        symbol: "N",
        atomicNumber: 7,
        massNumber: 14,
        meltingPoint: "-210.00 °C",
        boilingPoint: "-195.79 °C",
        atomicRadius: "56 pm",
        electrons: 7,
        protons: 7,
        neutrons: 7,
        electronicConfiguration: "1s² 2s² 2p³",
        yearOfDiscovery: 1772,
        discoveredBy: "Daniel Rutherford",
        groupNumber: 15,
        blockName: "p",
        periodNumber: 2,
        density: "0.0012506 g/L",
        image: "https://www.chemicalelements.com/images/elements/nitrogen.png",
        category: "nonmetals"
    },
    {
        name: "Oxygen",
        symbol: "O",
        atomicNumber: 8,
        massNumber: 16,
        meltingPoint: "-218.79 °C",
        boilingPoint: "-182.96 °C",
        atomicRadius: "60 pm",
        electrons: 8,
        protons: 8,
        neutrons: 8,
        electronicConfiguration: "1s² 2s² 2p⁴",
        yearOfDiscovery: 1774,
        discoveredBy: "Joseph Priestley",
        groupNumber: 16,
        blockName: "p",
        periodNumber: 2,
        density: "0.001429 g/L",
        image: "https://www.chemicalelements.com/images/elements/oxygen.png",
        category: "nonmetals"
    },
    {
        name: "Fluorine",
        symbol: "F",
        atomicNumber: 9,
        massNumber: 19,
        meltingPoint: "-219.67 °C",
        boilingPoint: "-188.12 °C",
        atomicRadius: "42 pm",
        electrons: 9,
        protons: 9,
        neutrons: 10,
        electronicConfiguration: "1s² 2s² 2p⁵",
        yearOfDiscovery: 1886,
        discoveredBy: "Henri Moissan",
        groupNumber: 17,
        blockName: "p",
        periodNumber: 2,
        density: "0.001696 g/L",
        image: "https://www.chemicalelements.com/images/elements/fluorine.png",
        category: "halogens"
    },
    {
        name: "Neon",
        symbol: "Ne",
        atomicNumber: 10,
        massNumber: 20,
        meltingPoint: "-248.59 °C",
        boilingPoint: "-246.05 °C",
        atomicRadius: "38 pm",
        electrons: 10,
        protons: 10,
        neutrons: 10,
        electronicConfiguration: "1s² 2s² 2p⁶",
        yearOfDiscovery: 1898,
        discoveredBy: "Sir William Ramsay",
        groupNumber: 18,
        blockName: "p",
        periodNumber: 2,
        density: "0.0008999 g/L",
        image: "https://www.chemicalelements.com/images/elements/neon.png",
        category: "noble-gases"
    },
    {
        name: "Sodium",
        symbol: "Na",
        atomicNumber: 11,
        massNumber: 23,
        meltingPoint: "97.72 °C",
        boilingPoint: "883 °C",
        atomicRadius: "186 pm",
        electrons: 11,
        protons: 11,
        neutrons: 12,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s¹",
        yearOfDiscovery: 1807,
        discoveredBy: "Sir Humphry Davy",
        groupNumber: 1,
        blockName: "s",
        periodNumber: 3,
        density: "0.968 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/sodium.png",
        category: "alkali"
    },
    {
        name: "Magnesium",
        symbol: "Mg",
        atomicNumber: 12,
        massNumber: 24,
        meltingPoint: "650 °C",
        boilingPoint: "1090 °C",
        atomicRadius: "160 pm",
        electrons: 12,
        protons: 12,
        neutrons: 12,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s²",
        yearOfDiscovery: 1808,
        discoveredBy: "Sir Humphry Davy",
        groupNumber: 2,
        blockName: "s",
        periodNumber: 3,
        density: "1.738 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/magnesium.png",
        category: "alkali-earth"
    },
    {
        name: "Aluminum",
        symbol: "Al",
        atomicNumber: 13,
        massNumber: 27,
        meltingPoint: "660.32 °C",
        boilingPoint: "2467 °C",
        atomicRadius: "143 pm",
        electrons: 13,
        protons: 13,
        neutrons: 14,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p¹",
        yearOfDiscovery: 1825,
        discoveredBy: "Hans Christian Ørsted",
        groupNumber: 13,
        blockName: "p",
        periodNumber: 3,
        density: "2.70 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/aluminum.png",
        category: "metals"
    },
    {
        name: "Silicon",
        symbol: "Si",
        atomicNumber: 14,
        massNumber: 28,
        meltingPoint: "1414 °C",
        boilingPoint: "2900 °C",
        atomicRadius: "111 pm",
        electrons: 14,
        protons: 14,
        neutrons: 14,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p²",
        yearOfDiscovery: 1824,
        discoveredBy: "Jöns Jacob Berzelius",
        groupNumber: 14,
        blockName: "p",
        periodNumber: 3,
        density: "2.3296 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/silicon.png",
        category: "metalloids"
    },
    {
        name: "Phosphorus",
        symbol: "P",
        atomicNumber: 15,
        massNumber: 31,
        meltingPoint: "44.15 °C",
        boilingPoint: "280 °C",
        atomicRadius: "110 pm",
        electrons: 15,
        protons: 15,
        neutrons: 16,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p³",
        yearOfDiscovery: 1669,
        discoveredBy: "Hennig Brand",
        groupNumber: 15,
        blockName: "p",
        periodNumber: 3,
        density: "1.82 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/phosphorus.png",
        category: "nonmetals"
    },
    {
        name: "Sulfur",
        symbol: "S",
        atomicNumber: 16,
        massNumber: 32,
        meltingPoint: "115.21 °C",
        boilingPoint: "444.6 °C",
        atomicRadius: "104 pm",
        electrons: 16,
        protons: 16,
        neutrons: 16,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁴",
        yearOfDiscovery: "Ancient",
        discoveredBy: "Multiple sources",
        groupNumber: 16,
        blockName: "p",
        periodNumber: 3,
        density: "2.067 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/sulfur.png",
        category: "nonmetals"
    }, 
    {
    
        name: "Sulfur",
        symbol: "S",
        atomicNumber: 16,
        massNumber: 32,
        meltingPoint: "115.21 °C",
        boilingPoint: "444.6 °C",
        atomicRadius: "104 pm",
        electrons: 16,
        protons: 16,
        neutrons: 16,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁴",
        yearOfDiscovery: "Ancient",
        discoveredBy: "Multiple sources",
        groupNumber: 16,
        blockName: "p",
        periodNumber: 3,
        density: "2.067 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/sulfur.png",
        category: "nonmetals"
    },
    {
        name: "Chlorine",
        symbol: "Cl",
        atomicNumber: 17,
        massNumber: 35,
        meltingPoint: "-101.5 °C",
        boilingPoint: "-34.04 °C",
        atomicRadius: "99 pm",
        electrons: 17,
        protons: 17,
        neutrons: 18,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁵",
        yearOfDiscovery: 1774,
        discoveredBy: "Joseph Priestley",
        groupNumber: 17,
        blockName: "p",
        periodNumber: 3,
        density: "0.003214 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/chlorine.png",
        category: "halogens"
    },
    {
        name: "Argon",
        symbol: "Ar",
        atomicNumber: 18,
        massNumber: 40,
        meltingPoint: "-189.35 °C",
        boilingPoint: "-185.85 °C",
        atomicRadius: "71 pm",
        electrons: 18,
        protons: 18,
        neutrons: 22,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶",
        yearOfDiscovery: 1894,
        discoveredBy: "Lord Rayleigh, Sir William Ramsay",
        groupNumber: 18,
        blockName: "p",
        periodNumber: 3,
        density: "0.001784 g/L",
        image: "https://www.chemicalelements.com/images/elements/argon.png",
        category: "noble-gases"
    },
    {
        name: "Potassium",
        symbol: "K",
        atomicNumber: 19,
        massNumber: 39,
        meltingPoint: "63.5 °C",
        boilingPoint: "759 °C",
        atomicRadius: "227 pm",
        electrons: 19,
        protons: 19,
        neutrons: 20,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹",
        yearOfDiscovery: 1807,
        discoveredBy: "Sir Humphry Davy",
        groupNumber: 1,
        blockName: "s",
        periodNumber: 4,
        density: "0.862 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/potassium.png",
        category: "alkali"
    },
    {
        name: "Calcium",
        symbol: "Ca",
        atomicNumber: 20,
        massNumber: 40,
        meltingPoint: "842 °C",
        boilingPoint: "1484 °C",
        atomicRadius: "197 pm",
        electrons: 20,
        protons: 20,
        neutrons: 20,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s²",
        yearOfDiscovery: 1808,
        discoveredBy: "Sir Humphry Davy",
        groupNumber: 2,
        blockName: "s",
        periodNumber: 4,
        density: "1.54 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/calcium.png",
        category: "alkali-earth"
    },
    {
        name: "Scandium",
        symbol: "Sc",
        atomicNumber: 21,
        massNumber: 45,
        meltingPoint: "1539 °C",
        boilingPoint: "2836 °C",
        atomicRadius: "160 pm",
        electrons: 21,
        protons: 21,
        neutrons: 24,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹",
        yearOfDiscovery: 1879,
        discoveredBy: "Lars Fredrik Nilson",
        groupNumber: 3,
        blockName: "d",
        periodNumber: 4,
        density: "2.985 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/scandium.png",
        category: "transition-metals"
    },
    {
        name: "Titanium",
        symbol: "Ti",
        atomicNumber: 22,
        massNumber: 48,
        meltingPoint: "1668 °C",
        boilingPoint: "3287 °C",
        atomicRadius: "147 pm",
        electrons: 22,
        protons: 22,
        neutrons: 26,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d²",
        yearOfDiscovery: 1791,
        discoveredBy: "William Gregor",
        groupNumber: 4,
        blockName: "d",
        periodNumber: 4,
        density: "4.506 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/titanium.png",
        category: "transition-metals"
    },
    {
        name: "Vanadium",
        symbol: "V",
        atomicNumber: 23,
        massNumber: 51,
        meltingPoint: "1910 °C",
        boilingPoint: "3380 °C",
        atomicRadius: "135 pm",
        electrons: 23,
        protons: 23,
        neutrons: 28,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d³",
        yearOfDiscovery: 1801,
        discoveredBy: "Andrés Manuel del Río",
        groupNumber: 5,
        blockName: "d",
        periodNumber: 4,
        density: "6.11 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/vanadium.png",
        category: "transition-metals"
    },
    {
        name: "Chromium",
        symbol: "Cr",
        atomicNumber: 24,
        massNumber: 52,
        meltingPoint: "1907 °C",
        boilingPoint: "2671 °C",
        atomicRadius: "129 pm",
        electrons: 24,
        protons: 24,
        neutrons: 28,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁵",
        yearOfDiscovery: 1797,
        discoveredBy: "Louis Nicolas Vauquelin",
        groupNumber: 6,
        blockName: "d",
        periodNumber: 4,
        density: "7.19 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/chromium.png",
        category: "transition-metals"
    },
    {
        name: "Manganese",
        symbol: "Mn",
        atomicNumber: 25,
        massNumber: 55,
        meltingPoint: "1244 °C",
        boilingPoint: "2095 °C",
        atomicRadius: "139 pm",
        electrons: 25,
        protons: 25,
        neutrons: 30,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁵",
        yearOfDiscovery: 1774,
        discoveredBy: "Johann Gottlieb Gahn",
        groupNumber: 7,
        blockName: "d",
        periodNumber: 4,
        density: "7.43 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/manganese.png",
        category: "transition-metals"
    },
    {
        name: "Iron",
        symbol: "Fe",
        atomicNumber: 26,
        massNumber: 56,
        meltingPoint: "1538 °C",
        boilingPoint: "2862 °C",
        atomicRadius: "126 pm",
        electrons: 26,
        protons: 26,
        neutrons: 30,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁶",
        yearOfDiscovery: "Ancient",
        discoveredBy: "Multiple sources",
        groupNumber: 8,
        blockName: "d",
        periodNumber: 4,
        density: "7.87 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/iron.png",
        category: "transition-metals"
    },
    {
        name: "Cobalt",
        symbol: "Co",
        atomicNumber: 27,
        massNumber: 59,
        meltingPoint: "1495 °C",
        boilingPoint: "2927 °C",
        atomicRadius: "125 pm",
        electrons: 27,
        protons: 27,
        neutrons: 32,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁷",
        yearOfDiscovery: 1735,
        discoveredBy: "Georg Brandt",
        groupNumber: 9,
        blockName: "d",
        periodNumber: 4,
        density: "8.90 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/cobalt.png",
        category: "transition-metals"
    },
    {
        name: "Nickel",
        symbol: "Ni",
        atomicNumber: 28,
        massNumber: 58,
        meltingPoint: "1455 °C",
        boilingPoint: "2913 °C",
        atomicRadius: "124 pm",
        electrons: 28,
        protons: 28,
        neutrons: 30,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁸",
        yearOfDiscovery: 1751,
        discoveredBy: "Axel Fredrik Cronstedt",
        groupNumber: 10,
        blockName: "d",
        periodNumber: 4,
        density: "8.908 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/nickel.png",
        category: "transition-metals"
    },
    {
        name: "Copper",
        symbol: "Cu",
        atomicNumber: 29,
        massNumber: 64,
        meltingPoint: "1084.62 °C",
        boilingPoint: "2562 °C",
        atomicRadius: "127 pm",
        electrons: 29,
        protons: 29,
        neutrons: 35,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s¹",
        yearOfDiscovery: "Ancient",
        discoveredBy: "Multiple sources",
        groupNumber: 11,
        blockName: "d",
        periodNumber: 4,
        density: "8.96 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/copper.png",
        category: "transition-metals"
    },
    {
        name: "Zinc",
        symbol: "Zn",
        atomicNumber: 30,
        massNumber: 65,
        meltingPoint: "419.58 °C",
        boilingPoint: "907 °C",
        atomicRadius: "139 pm",
        electrons: 30,
        protons: 30,
        neutrons: 35,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s²",
        yearOfDiscovery: 1746,
        discoveredBy: "Andreas Marggraf",
        groupNumber: 12,
        blockName: "d",
        periodNumber: 4,
        density: "7.14 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/zinc.png",
        category: "transition-metals"
    },
    {
        name: "Gallium",
        symbol: "Ga",
        atomicNumber: 31,
        massNumber: 69,
        meltingPoint: "29.76 °C",
        boilingPoint: "2204 °C",
        atomicRadius: "135 pm",
        electrons: 31,
        protons: 31,
        neutrons: 38,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p¹",
        yearOfDiscovery: 1875,
        discoveredBy: "Paul-Émile Lecoq de Boisbaudran",
        groupNumber: 13,
        blockName: "p",
        periodNumber: 4,
        density: "5.91 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/gallium.png",
        category: "metals"
    },
    {
        name: "Germanium",
        symbol: "Ge",
        atomicNumber: 32,
        massNumber: 73,
        meltingPoint: "938.25 °C",
        boilingPoint: "2833 °C",
        atomicRadius: "125 pm",
        electrons: 32,
        protons: 32,
        neutrons: 41,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p²",
        yearOfDiscovery: 1886,
        discoveredBy: "Clemens Winkler",
        groupNumber: 14,
        blockName: "p",
        periodNumber: 4,
        density: "5.323 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/germanium.png",
        category: "metalloids"
    },
    {
        name: "Arsenic",
        symbol: "As",
        atomicNumber: 33,
        massNumber: 74,
        meltingPoint: "817 °C",
        boilingPoint: "613 °C",
        atomicRadius: "119 pm",
        electrons: 33,
        protons: 33,
        neutrons: 41,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p³",
        yearOfDiscovery: "Ancient",
        discoveredBy: "Multiple sources",
        groupNumber: 15,
        blockName: "p",
        periodNumber: 4,
        density: "5.727 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/arsenic.png",
        category: "metalloids"
    },
    {
        name: "Selenium",
        symbol: "Se",
        atomicNumber: 34,
        massNumber: 79,
        meltingPoint: "221 °C",
        boilingPoint: "684.9 °C",
        atomicRadius: "116 pm",
        electrons: 34,
        protons: 34,
        neutrons: 45,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁴",
        yearOfDiscovery: 1817,
        discoveredBy: "Jöns Jacob Berzelius",
        groupNumber: 16,
        blockName: "p",
        periodNumber: 4,
        density: "4.81 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/selenium.png",
        category: "nonmetals"
    },
    {
        name: "Bromine",
        symbol: "Br",
        atomicNumber: 35,
        massNumber: 80,
        meltingPoint: "-7.2 °C",
        boilingPoint: "58.8 °C",
        atomicRadius: "114 pm",
        electrons: 35,
        protons: 35,
        neutrons: 45,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁵",
        yearOfDiscovery: 1826,
        discoveredBy: "Antoine-Jérôme Balard",
        groupNumber: 17,
        blockName: "p",
        periodNumber: 4,
        density: "3.1028 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/bromine.png",
        category: "halogens"
    },
    {
        name: "Krypton",
        symbol: "Kr",
        atomicNumber: 36,
        massNumber: 84,
        meltingPoint: "-157.36 °C",
        boilingPoint: "-153.22 °C",
        atomicRadius: "110 pm",
        electrons: 36,
        protons: 36,
        neutrons: 48,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶",
        yearOfDiscovery: 1898,
        discoveredBy: "Sir William Ramsay, Morris Travers",
        groupNumber: 18,
        blockName: "p",
        periodNumber: 4,
        density: "0.003749 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/krypton.png",
        category: "noble-gases"
    },
    {
        name: "Rubidium",
        symbol: "Rb",
        atomicNumber: 37,
        massNumber: 85,
        meltingPoint: "39.3 °C",
        boilingPoint: "688 °C",
        atomicRadius: "303 pm",
        electrons: 37,
        protons: 37,
        neutrons: 48,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 4p⁶ 5s¹",
        yearOfDiscovery: 1861,
        discoveredBy: "Gustav Kirchhoff, Robert Bunsen",
        groupNumber: 1,
        blockName: "s",
        periodNumber: 5,
        density: "1.532 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/rubidium.png",
        category: "alkali"
    },
    {
        name: "Strontium",
        symbol: "Sr",
        atomicNumber: 38,
        massNumber: 87,
        meltingPoint: "777 °C",
        boilingPoint: "1382 °C",
        atomicRadius: "249 pm",
        electrons: 38,
        protons: 38,
        neutrons: 49,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s²",
        yearOfDiscovery: 1790,
        discoveredBy: "Adair Crawford",
        groupNumber: 2,
        blockName: "s",
        periodNumber: 5,
        density: "2.64 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/strontium.png",
        category: "alkali-earth"
    },
    {
        name: "Yttrium",
        symbol: "Y",
        atomicNumber: 39,
        massNumber: 89,
        meltingPoint: "1526 °C",
        boilingPoint: "3337 °C",
        atomicRadius: "211 pm",
        electrons: 39,
        protons: 39,
        neutrons: 50,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹",
        yearOfDiscovery: 1794,
        discoveredBy: "Jöns Jakob Berzelius",
        groupNumber: 3,
        blockName: "d",
        periodNumber: 5,
        density: "4.472 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/yttrium.png",
        category: "transition-metals"
    },
    {
        name: "Zirconium",
        symbol: "Zr",
        atomicNumber: 40,
        massNumber: 91,
        meltingPoint: "1855 °C",
        boilingPoint: "4377 °C",
        atomicRadius: "211 pm",
        electrons: 40,
        protons: 40,
        neutrons: 51,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d²",
        yearOfDiscovery: 1789,
        discoveredBy: "Martin Heinrich Klaproth",
        groupNumber: 4,
        blockName: "d",
        periodNumber: 5,
        density: "6.52 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/zirconium.png",
        category: "transition-metals"
    },
    {
        name: "Niobium",
        symbol: "Nb",
        atomicNumber: 41,
        massNumber: 93,
        meltingPoint: "2477 °C",
        boilingPoint: "4744 °C",
        atomicRadius: "146 pm",
        electrons: 41,
        protons: 41,
        neutrons: 52,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁴",
        yearOfDiscovery: 1801,
        discoveredBy: "Charles Hatchett",
        groupNumber: 5,
        blockName: "d",
        periodNumber: 5,
        density: "8.57 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/niobium.png",
        category: "transition-metals"
    },
    {
        name: "Molybdenum",
        symbol: "Mo",
        atomicNumber: 42,
        massNumber: 98,
        meltingPoint: "2623 °C",
        boilingPoint: "4639 °C",
        atomicRadius: "139 pm",
        electrons: 42,
        protons: 42,
        neutrons: 56,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁵",
        yearOfDiscovery: 1778,
        discoveredBy: "Carl Wilhelm Scheele",
        groupNumber: 6,
        blockName: "d",
        periodNumber: 5,
        density: "10.28 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/molybdenum.png",
        category: "transition-metals"
    },
    {
        name: "Technetium",
        symbol: "Tc",
        atomicNumber: 43,
        massNumber: 99,
        meltingPoint: "2157 °C",
        boilingPoint: "4265 °C",
        atomicRadius: "138 pm",
        electrons: 43,
        protons: 43,
        neutrons: 56,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁵",
        yearOfDiscovery: 1937,
        discoveredBy: "Carlo Perrier, Emilio Segrè",
        groupNumber: 7,
        blockName: "d",
        periodNumber: 5,
        density: "11 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/technetium.png",
        category: "transition-metals"
    },
    {
        name: "Ruthenium",
        symbol: "Ru",
        atomicNumber: 44,
        massNumber: 101,
        meltingPoint: "2334 °C",
        boilingPoint: "4139 °C",
        atomicRadius: "134 pm",
        electrons: 44,
        protons: 44,
        neutrons: 57,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁷",
        yearOfDiscovery: 1844,
        discoveredBy: "Karl Ernst Claus",
        groupNumber: 8,
        blockName: "d",
        periodNumber: 5,
        density: "12.37 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/ruthenium.png",
        category: "transition-metals"
    },
    {
        name: "Rhodium",
        symbol: "Rh",
        atomicNumber: 45,
        massNumber: 103,
        meltingPoint: "1964 °C",
        boilingPoint: "3695 °C",
        atomicRadius: "135 pm",
        electrons: 45,
        protons: 45,
        neutrons: 58,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d⁸",
        yearOfDiscovery: 1803,
        discoveredBy: "William Hyde Wollaston",
        groupNumber: 9,
        blockName: "d",
        periodNumber: 5,
        density: "12.41 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/rhodium.png",
        category: "transition-metals"
    },
    {
        name: "Palladium",
        symbol: "Pd",
        atomicNumber: 46,
        massNumber: 106,
        meltingPoint: "1555 °C",
        boilingPoint: "2963 °C",
        atomicRadius: "137 pm",
        electrons: 46,
        protons: 46,
        neutrons: 60,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰",
        yearOfDiscovery: 1803,
        discoveredBy: "William Hyde Wollaston",
        groupNumber: 10,
        blockName: "d",
        periodNumber: 5,
        density: "12.02 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/palladium.png",
        category: "transition-metals"
    },
    {
        name: "Silver",
        symbol: "Ag",
        atomicNumber: 47,
        massNumber: 108,
        meltingPoint: "961.78 °C",
        boilingPoint: "2162 °C",
        atomicRadius: "144 pm",
        electrons: 47,
        protons: 47,
        neutrons: 61,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰",
        yearOfDiscovery: "Ancient",
        discoveredBy: "Multiple sources",
        groupNumber: 11,
        blockName: "d",
        periodNumber: 5,
        density: "10.49 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/silver.png",
        category: "transition-metals"
    },
    {
        name: "Cadmium",
        symbol: "Cd",
        atomicNumber: 48,
        massNumber: 112,
        meltingPoint: "321.07 °C",
        boilingPoint: "767 °C",
        atomicRadius: "151 pm",
        electrons: 48,
        protons: 48,
        neutrons: 64,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰",
        yearOfDiscovery: 1817,
        discoveredBy: "Friedrich Strohmeyer",
        groupNumber: 12,
        blockName: "d",
        periodNumber: 5,
        density: "8.65 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/cadmium.png",
        category: "transition-metals"
    },
    {
        name: "Indium",
        symbol: "In",
        atomicNumber: 49,
        massNumber: 115,
        meltingPoint: "156.6 °C",
        boilingPoint: "2072 °C",
        atomicRadius: "193 pm",
        electrons: 49,
        protons: 49,
        neutrons: 66,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p¹",
        yearOfDiscovery: 1863,
        discoveredBy: "Ferdinand Reich, Theodor Richter",
        groupNumber: 13,
        blockName: "p",
        periodNumber: 5,
        density: "7.31 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/indium.png",
        category: "metals"
    },
    {
        name: "Tin",
        symbol: "Sn",
        atomicNumber: 50,
        massNumber: 119,
        meltingPoint: "231.93 °C",
        boilingPoint: "2602 °C",
        atomicRadius: "217 pm",
        electrons: 50,
        protons: 50,
        neutrons: 69,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p²",
        yearOfDiscovery: "Ancient",
        discoveredBy: "Multiple sources",
        groupNumber: 14,
        blockName: "p",
        periodNumber: 5,
        density: "7.31 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/tin.png",
        category: "metals"
    },
    {
        name: "Antimony",
        symbol: "Sb",
        atomicNumber: 51,
        massNumber: 122,
        meltingPoint: "630.63 °C",
        boilingPoint: "1587 °C",
        atomicRadius: "202 pm",
        electrons: 51,
        protons: 51,
        neutrons: 71,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p³",
        yearOfDiscovery: "Ancient",
        discoveredBy: "Multiple sources",
        groupNumber: 15,
        blockName: "p",
        periodNumber: 5,
        density: "6.697 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/antimony.png",
        category: "metalloids"
    },
    {
        name: "Tellurium",
        symbol: "Te",
        atomicNumber: 52,
        massNumber: 125,
        meltingPoint: "449.51 °C",
        boilingPoint: "988 °C",
        atomicRadius: "206 pm",
        electrons: 52,
        protons: 52,
        neutrons: 73,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁴",
        yearOfDiscovery: 1782,
        discoveredBy: "Martin Heinrich Klaproth",
        groupNumber: 16,
        blockName: "p",
        periodNumber: 5,
        density: "6.24 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/tellurium.png",
        category: "metalloids"
    },
    {
        name: "Iodine",
        symbol: "I",
        atomicNumber: 53,
        massNumber: 127,
        meltingPoint: "113.7 °C",
        boilingPoint: "184.4 °C",
        atomicRadius: "198 pm",
        electrons: 53,
        protons: 53,
        neutrons: 74,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁵",
        yearOfDiscovery: 1811,
        discoveredBy: "Bernhard Riess",
        groupNumber: 17,
        blockName: "p",
        periodNumber: 5,
        density: "4.933 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/iodine.png",
        category: "halogens"
    },
    {
        name: "Xenon",
        symbol: "Xe",
        atomicNumber: 54,
        massNumber: 131,
        meltingPoint: "-111.7 °C",
        boilingPoint: "-108.1 °C",
        atomicRadius: "216 pm",
        electrons: 54,
        protons: 54,
        neutrons: 77,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁶",
        yearOfDiscovery: 1898,
        discoveredBy: "Sir William Ramsay, Morris Travers",
        groupNumber: 18,
        blockName: "p",
        periodNumber: 5,
        density: "0.005887 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/xenon.png",
        category: "noble-gases"
    },
    {
        name: "Caesium",
        symbol: "Cs",
        atomicNumber: 55,
        massNumber: 133,
        meltingPoint: "28.44 °C",
        boilingPoint: "671 °C",
        atomicRadius: "303 pm",
        electrons: 55,
        protons: 55,
        neutrons: 78,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 4p⁶ 5s² 5p⁶ 6s¹",
        yearOfDiscovery: 1860,
        discoveredBy: "Robert Bunsen, Gustav Kirchhoff",
        groupNumber: 1,
        blockName: "s",
        periodNumber: 6,
        density: "1.93 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/caesium.png",
        category: "alkali"
    },      
    {
                name: "Barium",
                symbol: "Ba",
                atomicNumber: 56,
                massNumber: 137,
                meltingPoint: "727 °C",
                boilingPoint: "1640 °C",
                atomicRadius: "253 pm",
                electrons: 56,
                protons: 56,
                neutrons: 81,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 4s² 4p⁶ 5s² 5p⁶ 6s²",
                yearOfDiscovery: 1774,
                discoveredBy: "Carl Wilhelm Scheele",
                groupNumber: 2,
                blockName: "s",
                periodNumber: 6,
                density: "3.62 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/barium.png",
                category: "alkali-earth"
            },
            {
                name: "Lanthanum",
                symbol: "La",
                atomicNumber: 57,
                massNumber: 138,
                meltingPoint: "921 °C",
                boilingPoint: "3464 °C",
                atomicRadius: "195 pm",
                electrons: 57,
                protons: 57,
                neutrons: 81,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 5p⁶ 4f¹",
                yearOfDiscovery: 1839,
                discoveredBy: "Carl Gustaf Mosander",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "6.15 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/lanthanum.png",
                category: "lanthanides"
            },
            {
                name: "Cerium",
                symbol: "Ce",
                atomicNumber: 58,
                massNumber: 140,
                meltingPoint: "798 °C",
                boilingPoint: "3443 °C",
                atomicRadius: "182 pm",
                electrons: 58,
                protons: 58,
                neutrons: 82,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f²",
                yearOfDiscovery: 1803,
                discoveredBy: "Jöns Jakob Berzelius, Wilhelm Hisinger",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "6.77 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/cerium.png",
                category: "lanthanides"
            },
            {
                name: "Praseodymium",
                symbol: "Pr",
                atomicNumber: 59,
                massNumber: 141,
                meltingPoint: "931 °C",
                boilingPoint: "3520 °C",
                atomicRadius: "182 pm",
                electrons: 59,
                protons: 59,
                neutrons: 82,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f³",
                yearOfDiscovery: 1885,
                discoveredBy: "Carl Auer von Welsbach",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "6.77 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/praseodymium.png",
                category: "lanthanides"
            },
            {
                name: "Neodymium",
                symbol: "Nd",
                atomicNumber: 60,
                massNumber: 144,
                meltingPoint: "1021 °C",
                boilingPoint: "3074 °C",
                atomicRadius: "180 pm",
                electrons: 60,
                protons: 60,
                neutrons: 84,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f⁴",
                yearOfDiscovery: 1885,
                discoveredBy: "Carl Auer von Welsbach",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "7.01 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/neodymium.png",
                category: "lanthanides"
            },
            {
                name: "Promethium",
                symbol: "Pm",
                atomicNumber: 61,
                massNumber: 145,
                meltingPoint: "1042 °C",
                boilingPoint: "3000 °C",
                atomicRadius: "180 pm",
                electrons: 61,
                protons: 61,
                neutrons: 84,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f⁵",
                yearOfDiscovery: 1945,
                discoveredBy: "J. A. Marinsky, H. D. McLain, L. E. Glendenin",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "7.26 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/promethium.png",
                category: "lanthanides"
            },
            {
                name: "Samarium",
                symbol: "Sm",
                atomicNumber: 62,
                massNumber: 150,
                meltingPoint: "1074 °C",
                boilingPoint: "1900 °C",
                atomicRadius: "179 pm",
                electrons: 62,
                protons: 62,
                neutrons: 88,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f⁶",
                yearOfDiscovery: 1853,
                discoveredBy: "Paul-Émile Lecoq de Boisbaudran",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "7.52 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/samarium.png",
                category: "lanthanides"
            },
            {
                name: "Europium",
                symbol: "Eu",
                atomicNumber: 63,
                massNumber: 152,
                meltingPoint: "1095 °C",
                boilingPoint: "1527 °C",
                atomicRadius: "177 pm",
                electrons: 63,
                protons: 63,
                neutrons: 89,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f⁷",
                yearOfDiscovery: 1896,
                discoveredBy: "François Auguste Victor Gaultier",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "5.24 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/europium.png",
                category: "lanthanides"
            },
       
        
            {
                name: "Gadolinium",
                symbol: "Gd",
                atomicNumber: 64,
                massNumber: 157,
                meltingPoint: "1313 °C",
                boilingPoint: "3273 °C",
                atomicRadius: "174 pm",
                electrons: 64,
                protons: 64,
                neutrons: 93,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f⁷",
                yearOfDiscovery: 1880,
                discoveredBy: "Jean Charles Galissard de Marignac",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "7.90 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/gadolinium.png",
                category: "lanthanides"
            },
            {
                name: "Terbium",
                symbol: "Tb",
                atomicNumber: 65,
                massNumber: 159,
                meltingPoint: "1356 °C",
                boilingPoint: "3230 °C",
                atomicRadius: "173 pm",
                electrons: 65,
                protons: 65,
                neutrons: 94,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f⁸",
                yearOfDiscovery: 1843,
                discoveredBy: "Carl Auer von Welsbach",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "8.23 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/terbium.png",
                category: "lanthanides"
            },
            {
                name: "Dysprosium",
                symbol: "Dy",
                atomicNumber: 66,
                massNumber: 162,
                meltingPoint: "1412 °C",
                boilingPoint: "2840 °C",
                atomicRadius: "171 pm",
                electrons: 66,
                protons: 66,
                neutrons: 96,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f⁹",
                yearOfDiscovery: 1886,
                discoveredBy: "Paul-Émile Lecoq de Boisbaudran",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "8.55 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/dysprosium.png",
                category: "lanthanides"
            },
            {
                name: "Holmium",
                symbol: "Ho",
                atomicNumber: 67,
                massNumber: 164,
                meltingPoint: "1474 °C",
                boilingPoint: "2720 °C",
                atomicRadius: "169 pm",
                electrons: 67,
                protons: 67,
                neutrons: 97,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f¹⁰",
                yearOfDiscovery: 1878,
                discoveredBy: "Per Teodor Cleve",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "8.79 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/holmium.png",
                category: "lanthanides"
            },
            {
                name: "Erbium",
                symbol: "Er",
                atomicNumber: 68,
                massNumber: 167,
                meltingPoint: "1526 °C",
                boilingPoint: "2868 °C",
                atomicRadius: "167 pm",
                electrons: 68,
                protons: 68,
                neutrons: 99,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f¹¹",
                yearOfDiscovery: 1843,
                discoveredBy: "Carl Auer von Welsbach",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "9.07 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/erbium.png",
                category: "lanthanides"
            },
            {
                name: "Thulium",
                symbol: "Tm",
                atomicNumber: 69,
                massNumber: 169,
                meltingPoint: "1818 °C",
                boilingPoint: "2223 °C",
                atomicRadius: "165 pm",
                electrons: 69,
                protons: 69,
                neutrons: 100,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f¹²",
                yearOfDiscovery: 1879,
                discoveredBy: "Per Teodor Cleve",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "9.32 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/thulium.png",
                category: "lanthanides"
            },
            {
                name: "Ytterbium",
                symbol: "Yb",
                atomicNumber: 70,
                massNumber: 173,
                meltingPoint: "824 °C",
                boilingPoint: "1196 °C",
                atomicRadius: "163 pm",
                electrons: 70,
                protons: 70,
                neutrons: 103,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f¹³",
                yearOfDiscovery: 1878,
                discoveredBy: "Carl Auer von Welsbach",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "6.57 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/ytterbium.png",
                category: "lanthanides"
            },
            {
                name: "Lutetium",
                symbol: "Lu",
                atomicNumber: 71,
                massNumber: 175,
                meltingPoint: "1663 °C",
                boilingPoint: "3315 °C",
                atomicRadius: "161 pm",
                electrons: 71,
                protons: 71,
                neutrons: 104,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4f¹⁴",
                yearOfDiscovery: 1907,
                discoveredBy: "Carl Auer von Welsbach",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 6,
                density: "9.84 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/lutetium.png",
                category: "lanthanides"
            },
            
            {
                name: "Hafnium",
                symbol: "Hf",
                atomicNumber: 72,
                massNumber: 178,
                meltingPoint: "2233 °C",
                boilingPoint: "4603 °C",
                atomicRadius: "159 pm",
                electrons: 72,
                protons: 72,
                neutrons: 106,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d²",
                yearOfDiscovery: 1923,
                discoveredBy: "Dirk Coster, Georg von Hevesy",
                groupNumber: 4,
                blockName: "d",
                periodNumber: 6,
                density: "13.31 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/hafnium.png",
                category: "transition-metals"
            },
            {
                name: "Tantalum",
                symbol: "Ta",
                atomicNumber: 73,
                massNumber: 180,
                meltingPoint: "3017 °C",
                boilingPoint: "5458 °C",
                atomicRadius: "157 pm",
                electrons: 73,
                protons: 73,
                neutrons: 107,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d³",
                yearOfDiscovery: 1802,
                discoveredBy: "Karl Wilhelm Scheele",
                groupNumber: 5,
                blockName: "d",
                periodNumber: 6,
                density: "16.69 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/tantalum.png",
                category: "transition-metals"
            },
            {
                name: "Tungsten",
                symbol: "W",
                atomicNumber: 74,
                massNumber: 184,
                meltingPoint: "3422 °C",
                boilingPoint: "5555 °C",
                atomicRadius: "154 pm",
                electrons: 74,
                protons: 74,
                neutrons: 110,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d⁴",
                yearOfDiscovery: 1783,
                discoveredBy: "Carl Wilhelm Scheele, Peter Woulfe",
                groupNumber: 6,
                blockName: "d",
                periodNumber: 6,
                density: "19.25 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/tungsten.png",
                category: "transition-metals"
            },
            {
                name: "Rhenium",
                symbol: "Re",
                atomicNumber: 75,
                massNumber: 186,
                meltingPoint: "3186 °C",
                boilingPoint: "5596 °C",
                atomicRadius: "152 pm",
                electrons: 75,
                protons: 75,
                neutrons: 111,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d⁵",
                yearOfDiscovery: 1925,
                discoveredBy: "Ida Noddack, Otto Berg",
                groupNumber: 7,
                blockName: "d",
                periodNumber: 6,
                density: "21.02 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/rhenium.png",
                category: "transition-metals"
            },
            {
                name: "Osmium",
                symbol: "Os",
                atomicNumber: 76,
                massNumber: 190,
                meltingPoint: "3033 °C",
                boilingPoint: "5027 °C",
                atomicRadius: "150 pm",
                electrons: 76,
                protons: 76,
                neutrons: 114,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d⁶",
                yearOfDiscovery: 1803,
                discoveredBy: "Smithson Tennant",
                groupNumber: 8,
                blockName: "d",
                periodNumber: 6,
                density: "22.59 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/osmium.png",
                category: "transition-metals"
            },
            {
                name: "Iridium",
                symbol: "Ir",
                atomicNumber: 77,
                massNumber: 192,
                meltingPoint: "2446 °C",
                boilingPoint: "4130 °C",
                atomicRadius: "148 pm",
                electrons: 77,
                protons: 77,
                neutrons: 115,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d⁷",
                yearOfDiscovery: 1803,
                discoveredBy: "Smithson Tennant",
                groupNumber: 9,
                blockName: "d",
                periodNumber: 6,
                density: "22.56 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/iridium.png",
                category: "transition-metals"
            },
            {
                name: "Platinum",
                symbol: "Pt",
                atomicNumber: 78,
                massNumber: 195,
                meltingPoint: "1768.3 °C",
                boilingPoint: "3825 °C",
                atomicRadius: "144 pm",
                electrons: 78,
                protons: 78,
                neutrons: 117,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d⁸",
                yearOfDiscovery: 1735,
                discoveredBy: "Antonio de Ulloa",
                groupNumber: 10,
                blockName: "d",
                periodNumber: 6,
                density: "21.45 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/platinum.png",
                category: "transition-metals"
            },
            {
                name: "Gold",
                symbol: "Au",
                atomicNumber: 79,
                massNumber: 197,
                meltingPoint: "1064 °C",
                boilingPoint: "2970 °C",
                atomicRadius: "144 pm",
                electrons: 79,
                protons: 79,
                neutrons: 118,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰",
                yearOfDiscovery: "Prehistoric",
                discoveredBy: "Unknown",
                groupNumber: 11,
                blockName: "d",
                periodNumber: 6,
                density: "19.32 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/gold.png",
                category: "transition-metals"
            },
            {
                name: "Mercury",
                symbol: "Hg",
                atomicNumber: 80,
                massNumber: 201,
                meltingPoint: "-38.83 °C",
                boilingPoint: "356.73 °C",
                atomicRadius: "151 pm",
                electrons: 80,
                protons: 80,
                neutrons: 121,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰",
                yearOfDiscovery: "Prehistoric",
                discoveredBy: "Unknown",
                groupNumber: 12,
                blockName: "d",
                periodNumber: 6,
                density: "13.534 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/mercury.png",
                category: "transition-metals"
            },
        
            {
                name: "Thallium",
                symbol: "Tl",
                atomicNumber: 81,
                massNumber: 204,
                meltingPoint: "304 °C",
                boilingPoint: "1473 °C",
                atomicRadius: "150 pm",
                electrons: 81,
                protons: 81,
                neutrons: 123,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰",
                yearOfDiscovery: 1861,
                discoveredBy: "Claude-Auguste Lamy",
                groupNumber: 13,
                blockName: "p",
                periodNumber: 6,
                density: "11.85 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/thallium.png",
                category: "post-transition-metals"
            },
            {
                name: "Lead",
                symbol: "Pb",
                atomicNumber: 82,
                massNumber: 207,
                meltingPoint: "327.46 °C",
                boilingPoint: "1749 °C",
                atomicRadius: "154 pm",
                electrons: 82,
                protons: 82,
                neutrons: 125,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: "Ancient",
                discoveredBy: "Unknown",
                groupNumber: 14,
                blockName: "p",
                periodNumber: 6,
                density: "11.34 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/lead.png",
                category: "post-transition-metals"
            },
            {
                name: "Bismuth",
                symbol: "Bi",
                atomicNumber: 83,
                massNumber: 209,
                meltingPoint: "271.5 °C",
                boilingPoint: "1560 °C",
                atomicRadius: "143 pm",
                electrons: 83,
                protons: 83,
                neutrons: 126,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1753,
                discoveredBy: "Claude-François Geoffroy",
                groupNumber: 15,
                blockName: "p",
                periodNumber: 6,
                density: "9.78 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/bismuth.png",
                category: "post-transition-metals"
            },
            {
                name: "Polonium",
                symbol: "Po",
                atomicNumber: 84,
                massNumber: 210,
                meltingPoint: "254 °C",
                boilingPoint: "962 °C",
                atomicRadius: "135 pm",
                electrons: 84,
                protons: 84,
                neutrons: 126,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1898,
                discoveredBy: "Marie Curie, Pierre Curie",
                groupNumber: 16,
                blockName: "p",
                periodNumber: 6,
                density: "9.32 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/polonium.png",
                category: "metalloids"
            },
            {
                name: "Astatine",
                symbol: "At",
                atomicNumber: 85,
                massNumber: 210,
                meltingPoint: "302 °C",
                boilingPoint: "337 °C",
                atomicRadius: "140 pm",
                electrons: 85,
                protons: 85,
                neutrons: 125,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1940,
                discoveredBy: "Dale R. Corson, Kenneth Ross MacKenzie",
                groupNumber: 17,
                blockName: "p",
                periodNumber: 6,
                density: "6.2 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/astatine.png",
                category: "halogens"
            },
            {
                name: "Radon",
                symbol: "Rn",
                atomicNumber: 86,
                massNumber: 222,
                meltingPoint: "-71 °C",
                boilingPoint: "-61.7 °C",
                atomicRadius: "138 pm",
                electrons: 86,
                protons: 86,
                neutrons: 136,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1899,
                discoveredBy: "Frederick Dorn",
                groupNumber: 18,
                blockName: "p",
                periodNumber: 6,
                density: "0.009 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/radon.png",
                category: "noble-gases"
            },
            {
                name: "Francium",
                symbol: "Fr",
                atomicNumber: 87,
                massNumber: 223,
                meltingPoint: "27 °C",
                boilingPoint: "677 °C",
                atomicRadius: "223 pm",
                electrons: 87,
                protons: 87,
                neutrons: 136,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1939,
                discoveredBy: "Marguerite Perey",
                groupNumber: 1,
                blockName: "s",
                periodNumber: 7,
                density: "1.87 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/francium.png",
                category: "alkali-metals"
            },
            {
                name: "Radium",
                symbol: "Ra",
                atomicNumber: 88,
                massNumber: 226,
                meltingPoint: "700 °C",
                boilingPoint: "1413 °C",
                atomicRadius: "195 pm",
                electrons: 88,
                protons: 88,
                neutrons: 138,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1898,
                discoveredBy: "Marie Curie, Pierre Curie",
                groupNumber: 2,
                blockName: "s",
                periodNumber: 7,
                density: "5.5 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/radium.png",
                category: "alkaline-earth-metals"
            },
        
        
            {
                name: "Actinium",
                symbol: "Ac",
                atomicNumber: 89,
                massNumber: 227,
                meltingPoint: "1050 °C",
                boilingPoint: "3200 °C",
                atomicRadius: "180 pm",
                electrons: 89,
                protons: 89,
                neutrons: 138,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1899,
                discoveredBy: "Friedrich Oskar Giesel",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 7,
                density: "1.87 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/actinium.png",
                category: "actinides"
            },
            {
                name: "Thorium",
                symbol: "Th",
                atomicNumber: 90,
                massNumber: 232,
                meltingPoint: "1750 °C",
                boilingPoint: "4790 °C",
                atomicRadius: "175 pm",
                electrons: 90,
                protons: 90,
                neutrons: 142,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1828,
                discoveredBy: "Jöns Jacob Berzelius",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 7,
                density: "11.72 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/thorium.png",
                category: "actinides"
            },
            {
                name: "Protactinium",
                symbol: "Pa",
                atomicNumber: 91,
                massNumber: 231,
                meltingPoint: "1568 °C",
                boilingPoint: "4130 °C",
                atomicRadius: "180 pm",
                electrons: 91,
                protons: 91,
                neutrons: 140,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1899,
                discoveredBy: "Otto Hahn, Lise Meitner",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 7,
                density: "15.37 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/protactinium.png",
                category: "actinides"
            },
            {
                name: "Uranium",
                symbol: "U",
                atomicNumber: 92,
                massNumber: 238,
                meltingPoint: "1132 °C",
                boilingPoint: "4131 °C",
                atomicRadius: "175 pm",
                electrons: 92,
                protons: 92,
                neutrons: 146,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1789,
                discoveredBy: "Martin Heinrich Klaproth",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 7,
                density: "18.95 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/uranium.png",
                category: "actinides"
            },
            {
                name: "Neptunium",
                symbol: "Np",
                atomicNumber: 93,
                massNumber: 237,
                meltingPoint: "644 °C",
                boilingPoint: "4131 °C",
                atomicRadius: "180 pm",
                electrons: 93,
                protons: 93,
                neutrons: 144,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1940,
                discoveredBy: "Glenn T. Seaborg",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 7,
                density: "20.45 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/neptunium.png",
                category: "actinides"
            },
            {
                name: "Plutonium",
                symbol: "Pu",
                atomicNumber: 94,
                massNumber: 244,
                meltingPoint: "640 °C",
                boilingPoint: "3235 °C",
                atomicRadius: "175 pm",
                electrons: 94,
                protons: 94,
                neutrons: 150,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1940,
                discoveredBy: "Glenn T. Seaborg",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 7,
                density: "19.86 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/plutonium.png",
                category: "actinides"
            },
            {
                name: "Americium",
                symbol: "Am",
                atomicNumber: 95,
                massNumber: 243,
                meltingPoint: "1176 °C",
                boilingPoint: "2880 °C",
                atomicRadius: "180 pm",
                electrons: 95,
                protons: 95,
                neutrons: 148,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1944,
                discoveredBy: "Glenn T. Seaborg",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 7,
                density: "13.67 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/americium.png",
                category: "actinides"
            },
            {
                name: "Curium",
                symbol: "Cm",
                atomicNumber: 96,
                massNumber: 247,
                meltingPoint: "1340 °C",
                boilingPoint: "3000 °C",
                atomicRadius: "180 pm",
                electrons: 96,
                protons: 96,
                neutrons: 151,
                electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
                yearOfDiscovery: 1944,
                discoveredBy: "Glenn T. Seaborg",
                groupNumber: 3,
                blockName: "f",
                periodNumber: 7,
                density: "13.51 g/cm³",
                image: "https://www.chemicalelements.com/images/elements/curium.png",
                category: "actinides"
            },
        
    {
        name: "Berkelium",
        symbol: "Bk",
        atomicNumber: 97,
        massNumber: 247,
        meltingPoint: "986 °C",
        boilingPoint: "Unknown",
        atomicRadius: "180 pm",
        electrons: 97,
        protons: 97,
        neutrons: 150,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1949,
        discoveredBy: "Glenn T. Seaborg",
        groupNumber: 3,
        blockName: "f",
        periodNumber: 7,
        density: "14.78 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/berkelium.png",
        category: "actinides"
    },
    {
        name: "Californium",
        symbol: "Cf",
        atomicNumber: 98,
        massNumber: 251,
        meltingPoint: "900 °C",
        boilingPoint: "1470 °C",
        atomicRadius: "180 pm",
        electrons: 98,
        protons: 98,
        neutrons: 153,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1950,
        discoveredBy: "Glenn T. Seaborg",
        groupNumber: 3,
        blockName: "f",
        periodNumber: 7,
        density: "15.10 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/californium.png",
        category: "actinides"
    },
    {
        name: "Einsteinium",
        symbol: "Es",
        atomicNumber: 99,
        massNumber: 252,
        meltingPoint: "860 °C",
        boilingPoint: "Unknown",
        atomicRadius: "180 pm",
        electrons: 99,
        protons: 99,
        neutrons: 153,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1952,
        discoveredBy: "Albert Ghiorso, Glenn T. Seaborg",
        groupNumber: 3,
        blockName: "f",
        periodNumber: 7,
        density: "8.8 g/cm³",
        image: "https://www.chemicalelements.com/images/elements/einsteinium.png",
        category: "actinides"
    },
    {
        name: "Fermium",
        symbol: "Fm",
        atomicNumber: 100,
        massNumber: 257,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "180 pm",
        electrons: 100,
        protons: 100,
        neutrons: 157,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1952,
        discoveredBy: "Albert Ghiorso, Glenn T. Seaborg",
        groupNumber: 3,
        blockName: "f",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/fermium.png",
        category: "actinides"
    },
    {
        name: "Mendelevium",
        symbol: "Md",
        atomicNumber: 101,
        massNumber: 258,
        meltingPoint: "1100 °C",
        boilingPoint: "Unknown",
        atomicRadius: "180 pm",
        electrons: 101,
        protons: 101,
        neutrons: 157,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1955,
        discoveredBy: "Albert Ghiorso, Glenn T. Seaborg",
        groupNumber: 3,
        blockName: "f",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/mendelevium.png",
        category: "actinides"
    },
    {
        name: "Nobelium",
        symbol: "No",
        atomicNumber: 102,
        massNumber: 259,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "180 pm",
        electrons: 102,
        protons: 102,
        neutrons: 157,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1957,
        discoveredBy: "Albert Ghiorso, Glenn T. Seaborg",
        groupNumber: 3,
        blockName: "f",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/nobelium.png",
        category: "actinides"
    },
    {
        name: "Lawrencium",
        symbol: "Lr",
        atomicNumber: 103,
        massNumber: 262,
        meltingPoint: "1627 °C",
        boilingPoint: "Unknown",
        atomicRadius: "180 pm",
        electrons: 103,
        protons: 103,
        neutrons: 159,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1961,
        discoveredBy: "Albert Ghiorso, Glenn T. Seaborg",
        groupNumber: 3,
        blockName: "f",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/lawrencium.png",
        category: "actinides"
    },
    {
        name: "Rutherfordium",
        symbol: "Rf",
        atomicNumber: 104,
        massNumber: 267,
        meltingPoint: "2400 °C",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 104,
        protons: 104,
        neutrons: 163,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1969,
        discoveredBy: "Joint Institute for Nuclear Research",
        groupNumber: 4,
        blockName: "d",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/rutherfordium.png",
        category: "transition-metals"
    },


    {
        name: "Dubnium",
        symbol: "Db",
        atomicNumber: 105,
        massNumber: 268,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 105,
        protons: 105,
        neutrons: 163,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1970,
        discoveredBy: "Joint Institute for Nuclear Research",
        groupNumber: 5,
        blockName: "d",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/dubnium.png",
        category: "transition-metals"
    },
    {
        name: "Seaborgium",
        symbol: "Sg",
        atomicNumber: 106,
        massNumber: 271,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 106,
        protons: 106,
        neutrons: 165,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1974,
        discoveredBy: "Lawrence Berkeley National Laboratory",
        groupNumber: 6,
        blockName: "d",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/seaborgium.png",
        category: "transition-metals"
    },
    {
        name: "Bohrium",
        symbol: "Bh",
        atomicNumber: 107,
        massNumber: 270,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 107,
        protons: 107,
        neutrons: 163,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1981,
        discoveredBy: "Research Institute for Nuclear Chemistry",
        groupNumber: 7,
        blockName: "d",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/bohrium.png",
        category: "transition-metals"
    },
    {
        name: "Hassium",
        symbol: "Hs",
        atomicNumber: 108,
        massNumber: 277,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 108,
        protons: 108,
        neutrons: 169,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1984,
        discoveredBy: "Research Institute for Nuclear Chemistry",
        groupNumber: 8,
        blockName: "d",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/hassium.png",
        category: "transition-metals"
    },
    {
        name: "Meitnerium",
        symbol: "Mt",
        atomicNumber: 109,
        massNumber: 278,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 109,
        protons: 109,
        neutrons: 169,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1982,
        discoveredBy: "GSI Helmholtz Centre for Heavy Ion Research",
        groupNumber: 9,
        blockName: "d",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/meitnerium.png",
        category: "transition-metals"
    },
    {
        name: "Darmstadtium",
        symbol: "Ds",
        atomicNumber: 110,
        massNumber: 281,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 110,
        protons: 110,
        neutrons: 171,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1994,
        discoveredBy: "GSI Helmholtz Centre for Heavy Ion Research",
        groupNumber: 10,
        blockName: "d",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/darmstadtium.png",
        category: "transition-metals"
    },
    {
        name: "Roentgenium",
        symbol: "Rg",
        atomicNumber: 111,
        massNumber: 280,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 111,
        protons: 111,
        neutrons: 169,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1994,
        discoveredBy: "GSI Helmholtz Centre for Heavy Ion Research",
        groupNumber: 11,
        blockName: "d",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/roentgenium.png",
        category: "transition-metals"
    },
    {
        name: "Copernicium",
        symbol: "Cn",
        atomicNumber: 112,
        massNumber: 285,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 112,
        protons: 112,
        neutrons: 173,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1996,
        discoveredBy: "GSI Helmholtz Centre for Heavy Ion Research",
        groupNumber: 12,
        blockName: "d",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/copernicium.png",
        category: "transition-metals"
    },
    {
        name: "Nihonium",
        symbol: "Nh",
        atomicNumber: 113,
        massNumber: 284,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 113,
        protons: 113,
        neutrons: 171,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 2003,
        discoveredBy: "RIKEN Nishina Center for Accelerator-Based Science",
        groupNumber: 13,
        blockName: "p",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/nihonium.png",
        category: "post-transition-metals"
    },
    {
        name: "Flerovium",
        symbol: "Fl",
        atomicNumber: 114,
        massNumber: 289,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 114,
        protons: 114,
        neutrons: 175,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 1998,
        discoveredBy: "Joint Institute for Nuclear Research (Russia)",
        groupNumber: 14,
        blockName: "p",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/flerovium.png",
        category: "post-transition-metals"
    },
    {
        name: "Moscovium",
        symbol: "Mc",
        atomicNumber: 115,
        massNumber: 288,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 115,
        protons: 115,
        neutrons: 173,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 2004,
        discoveredBy: "Joint Institute for Nuclear Research (Russia)",
        groupNumber: 15,
        blockName: "p",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/moscovium.png",
        category: "post-transition-metals"
    },
    {
        name: "Livermorium",
        symbol: "Lv",
        atomicNumber: 116,
        massNumber: 293,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 116,
        protons: 116,
        neutrons: 177,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 2000,
        discoveredBy: "Lawrence Livermore National Laboratory",
        groupNumber: 16,
        blockName: "p",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/livermorium.png",
        category: "post-transition-metals"
    },
    {
        name: "Tennessine",
        symbol: "Ts",
        atomicNumber: 117,
        massNumber: 294,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 117,
        protons: 117,
        neutrons: 177,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 2010,
        discoveredBy: "Joint Institute for Nuclear Research",
        groupNumber: 17,
        blockName: "p",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/tennessine.png",
        category: "halogens"
    },
    {
        name: "Oganesson",
        symbol: "Og",
        atomicNumber: 118,
        massNumber: 294,
        meltingPoint: "Unknown",
        boilingPoint: "Unknown",
        atomicRadius: "Unknown",
        electrons: 118,
        protons: 118,
        neutrons: 176,
        electronicConfiguration: "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶ 4d¹⁰ 5s² 4d¹⁰ 5p⁶",
        yearOfDiscovery: 2002,
        discoveredBy: "Joint Institute for Nuclear Research",
        groupNumber: 18,
        blockName: "p",
        periodNumber: 7,
        density: "Unknown",
        image: "https://www.chemicalelements.com/images/elements/oganesson.png",
        category: "noble-gases"
    }
];

const periodicTableElement = document.getElementById("periodicTable");

function renderPeriodicTable() {
    elements.forEach(element => {
        const elementDiv = document.createElement("div");
        elementDiv.classList.add("element", element.category);
        elementDiv.dataset.element = element.symbol;
        elementDiv.innerHTML = `
            <img src="${element.image}" alt="${element.name}">
            <p>${element.symbol}</p>
            <p>${element.atomicNumber}</p>
        `;
        
        elementDiv.addEventListener("click", () => displayElementDetails(element));
        periodicTableElement.appendChild(elementDiv);
    });
}

function displayElementDetails(element) {
    const detailsContent = document.getElementById("detailsContent");
    detailsContent.innerHTML = `
        <p><strong>Name:</strong> ${element.name}</p>
        <p><strong>Symbol:</strong> ${element.symbol}</p>
        <p><strong>Atomic Number:</strong> ${element.atomicNumber}</p>
        <p><strong>Mass Number:</strong> ${element.massNumber}</p>
        <p><strong>Melting Point:</strong> ${element.meltingPoint}</p>
        <p><strong>Boiling Point:</strong> ${element.boilingPoint}</p>
        <p><strong>Atomic Radius:</strong> ${element.atomicRadius}</p>
        <p><strong>Electrons:</strong> ${element.electrons}</p>
        <p><strong>Protons:</strong> ${element.protons}</p>
        <p><strong>Neutrons:</strong> ${element.neutrons}</p>
        <p><strong>Electronic Configuration:</strong> ${element.electronicConfiguration}</p>
        <p><strong>Year of Discovery:</strong> ${element.yearOfDiscovery}</p>
        <p><strong>Discovered By:</strong> ${element.discoveredBy}</p>
        <p><strong>Group Number:</strong> ${element.groupNumber}</p>
        <p><strong>Block Name:</strong> ${element.blockName}</p>
        <p><strong>Period Number:</strong> ${element.periodNumber}</p>
        <p><strong>Density:</strong> ${element.density}</p>
    `;
    document.getElementById("elementDetails").style.display = "block";
}
renderPeriodicTable();
                             // JavaScript to render elements in a proper periodic table layout
document.addEventListener("DOMContentLoaded", () => {
    const periodicTableContainer = document.getElementById("periodicTable");

    elements.forEach((element) => {
        const elementDiv = document.createElement("div");
        elementDiv.classList.add("element", element.category);
        elementDiv.style.gridColumn = element.groupNumber; // Place elements in correct group (column)
        elementDiv.style.gridRow = element.periodNumber; // Place elements in correct period (row)

        elementDiv.innerHTML = `
            <p>${element.symbol}</p>
            <p>${element.atomicNumber}</p>
        `;

        // Add hover event for showing element details
        elementDiv.addEventListener("mouseenter", () => showElementDetails(element));

        // Add click event for element interactivity
        elementDiv.addEventListener("click", () => displayElementModal(element));

        periodicTableContainer.appendChild(elementDiv);
    });
});

function showElementDetails(element) {
    const detailsContent = document.getElementById("detailsContent");
    detailsContent.innerHTML = `
        <img src="${element.image}" alt="${element.name}">
        <p><strong>Name:</strong> ${element.name}</p>
        <p><strong>Atomic Number:</strong> ${element.atomicNumber}</p>
        <p><strong>Symbol:</strong> ${element.symbol}</p>
        <p><strong>Category:</strong> ${element.category}</p>
        <p><strong>Electronic Configuration:</strong> ${element.electronicConfiguration}</p>
    `;
    document.getElementById("elementDetails").style.display = "block";
}

function displayElementModal(element) {
    // Modal or any other interactivity logic
    alert(`You clicked on ${element.name}`);
}
        